name: Deploy to AWS S3
description: Deploy to AWS S3
inputs:
  bucket: 
    description: 'The S3 Bucket name'
    required: true
  bucket-region:
    description: 'the region of S3 Bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Dist folder'
    required: true
outputs:
  website-url:
    description: 'The URL of website deployed'
  
runs:
  using: 'docker'
  image: 'Dockerfile'