name: 'Upload Artifacts'
decription: ' Uploading artifacts for a job'
inputs:
  artifact-name:
    description: 'Files that should be given to artifact'
    required: true
    default: dist-hill
  path:
    description: 'Path that should be uploaded for artifact'
    required: true
    default: dist-hill
outputs:
  uploaded:
    description: 'Message to display that artifact was uploaded'
    value: ${{ steps.upload-artifact.outputs.result }}
runs:
  using: composite
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }} 
        path: ${{ inputs.path }} 
    - name: Artifact result
      id: upload-artifact
      if: steps.upload-artifact.outputs.outcome== 'true'
      run: |
        echo "::set-output name=result::successfully uploaded ..."
      shell: bash
