name: 'Upload Artifacts'
decription: ' Uploading artifacts for a job'
inputs:
  artifact-name:
    description: 'Files that should be given to artifact'
    required: true
    default: dist-hill
  path:
    description: 'Path that should be uploaded for artifact'
    required: true
    default: dist-hill

runs:
  using: composite
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }} 
        path: ${{ inputs.path }} 